### ISSUE TITLE
Request: prompt saving, settings saving

### ISSUE THREAD

**Issue by HAV0X1014** [daniandtheweb/sd.cpp-webui#2]
It would be nice if settings and prompts could be saved for later. If possible, named 'configs' would be great.
I love the work that has been put into this project so far, it's a miracle to have simple image generation like this!

**Comment by daniandtheweb** [comment]
That's a great idea. I'll try to implement it later.

**Comment by daniandtheweb** [comment]
For now I've implemented a simple saving for the prompts. I still have to clean up the code and refactor some things before doing the same for the settings but I think it's coming out quite nicely. Take a look at it and tell me what do you think.

**Comment by HAV0X1014** [comment]
The prompt saving works wonderfully! A suggestion, don't allow whitespace as a name for prompts, and dont allow names for prompts to end with whitespace.

**Comment by daniandtheweb** [comment]
I've just pushed an update that adds the missing upscaling option and improves the saving function by not allowing blank names and stripping whitespaces from the used names.
