### ISSUE TITLE
Flux, t5xxl , clip models support

### ISSUE THREAD

**Issue by pedx78** [daniandtheweb/sd.cpp-webui#3]
Are Flux, t5xxl , clip models supported ?
I dont see a way  to importthem via the webui.

**Comment by daniandtheweb** [comment]
For now it isn't, I'll add support for it in a couple of days, I don't have access to my pc for now.

**Comment by daniandtheweb** [comment]
I've just pushed an update that adds support for FLUX in txt2img. It's still a wip as I have to refactor lots of stuff. Let me know how it works. You may have to delete the config.json.

**Comment by daniandtheweb** [comment]
I've made some updates and FLUX should now be fully supported.
